# -*- coding: utf-8 -*-
"""Apply common Vietnamese body-text diacritic fixes across component reports."""
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FILES = [
    "docs/component-reports/Frontend-Report.vi.docx",
    "docs/component-reports/Backend-Report.vi.docx",
    "docs/component-reports/Odysseus-Report.vi.docx",
    "docs/component-reports/ODF-Report.vi.docx",
]

# Longest phrases first to avoid partial overwrite issues.
PAIRS = [
    ("khong duoc phep", "không được phép"),
    ("khong duoc", "không được"),
    ("khong phai", "không phải"),
    ("khong thay", "không thay"),
    ("khong chi", "không chỉ"),
    ("khong co", "không có"),
    ("khong tu", "không tự"),
    ("khong bat", "không bắt"),
    ("khong xoa", "không xóa"),
    ("khong gop", "không gộp"),
    ("khong inject", "không inject"),
    ("khong affiliate", "không affiliate"),
    ("khong dual-write", "không dual-write"),
    ("khong noi", "không nối"),
    ("khong thuc thi", "không thực thi"),
    ("khong truncate", "không truncate"),
    ("khong commit", "không commit"),
    ("khong dung", "không dùng"),
    ("khong can", "không cần"),
    ("khong thuoc", "không thuộc"),
    ("khong mo", "không mở"),
    ("khong ghi", "không ghi"),
    ("khong start", "không start"),
    ("khong expose", "không expose"),
    ("khong coi", "không coi"),
    ("khong nang", "không nâng"),
    ("khong over-claim", "không over-claim"),
    ("khong sua", "không sửa"),
    ("khong dong nghia", "không đồng nghĩa"),
    ("la ung dung", "là ứng dụng"),
    ("la lop", "là lớp"),
    ("la dich vu", "là dịch vụ"),
    ("la trung tam", "là trung tâm"),
    ("la thanh phan", "là thành phần"),
    ("la nen tang", "là nền tảng"),
    ("la be mat", "là bề mặt"),
    ("la trai tim", "là trái tim"),
    ("la secondary", "là secondary"),
    ("va cac", "và các"),
    ("va optional", "và optional"),
    ("va ghi", "và ghi"),
    ("va ban do", "và bản đồ"),
    ("va routing", "và routing"),
    ("va module", "và module"),
    ("va hierarchy", "và hierarchy"),
    ("va background", "và background"),
    ("va persistence", "và persistence"),
    ("va dual-write", "và dual-write"),
    ("va health", "và health"),
    ("va backfill", "và backfill"),
    ("va delivery", "và delivery"),
    ("va migration", "và migration"),
    ("va kiem thu", "và kiểm thử"),
    ("va troubleshooting", "và troubleshooting"),
    ("va khuyen nghi", "và khuyến nghị"),
    ("va governance", "và governance"),
    ("va visual", "và visual"),
    ("va tools", "và tools"),
    ("va embeddings", "và embeddings"),
    ("va MCP", "và MCP"),
    ("cho van hanh", "cho vận hành"),
    ("cho UI", "cho UI"),
    ("cua FII", "của FII"),
    ("cua duong", "của đường"),
    ("trong monorepo", "trong monorepo"),
    ("trong kien truc", "trong kiến trúc"),
    ("trong he sinh thai", "trong hệ sinh thái"),
    ("trong transaction", "trong transaction"),
    ("trong setup", "trong setup"),
    ("trong incident", "trong incident"),
    ("du lieu van hanh", "dữ liệu vận hành"),
    ("du lieu", "dữ liệu"),
    ("van hanh", "vận hành"),
    ("quan tri", "quản trị"),
    ("man hinh", "màn hình"),
    ("vai tro", "vai trò"),
    ("ban do", "bản đồ"),
    ("phia client", "phía client"),
    ("ranh gioi", "ranh giới"),
    ("bao mat", "bảo mật"),
    ("that van nam", "thật vẫn nằm"),
    ("che do demo", "chế độ demo"),
    ("de trinh dien", "để trình diễn"),
    ("thao tac ghi", "thao tác ghi"),
    ("gia lap thanh cong", "giả lập thành công"),
    ("Pham vi thu muc", "Phạm vi thư mục"),
    ("truc tiep", "trực tiếp"),
    ("moi du lieu", "mọi dữ liệu"),
    ("di qua", "đi qua"),
    ("Luong end-to-end", "Luồng end-to-end"),
    ("dung sau", "đứng sau"),
    ("goi REST", "gọi REST"),
    ("neu session", "nếu session"),
    ("theo scope", "theo scope"),
    ("bat buoc", "bắt buộc"),
    ("de UI chay", "để UI chạy"),
    ("Duoc phep", "Được phép"),
    ("hien thi", "hiển thị"),
    ("cau hinh", "cấu hình"),
    ("co quyen", "có quyền"),
    ("chi view", "chỉ view"),
    ("chi ADMIN", "chỉ ADMIN"),
    ("chi tra", "chỉ trả"),
    ("chi trusted", "chỉ trusted"),
    ("chi gui", "chỉ gửi"),
    ("chi opt-in", "chỉ opt-in"),
    ("chi synthetic", "chỉ synthetic"),
    ("giam initial", "giảm initial"),
    ("kiem tra", "kiểm tra"),
    ("thuong co", "thường có"),
    ("tach khoi", "tách khỏi"),
    ("tap trung", "tập trung"),
    ("mac dinh", "mặc định"),
    ("phan tich san luong", "phân tích sản lượng"),
    ("trang thai", "trạng thái"),
    ("ho tro", "hỗ trợ"),
    ("nhan dien", "nhận diện"),
    ("phan anh", "phản ánh"),
    ("kich hoat", "kích hoạt"),
    ("cho demo", "cho demo"),
    ("khong thay production", "không thay production"),
    ("dinh nghia", "định nghĩa"),
    ("full tru", "full trừ"),
    ("dung map", "dùng map"),
    ("van enforce", "vẫn enforce"),
    ("moi request", "mọi request"),
    ("tu VITE", "từ VITE"),
    ("hoac /api", "hoặc /api"),
    ("neu co", "nếu có"),
    ("lien quan", "liên quan"),
    ("neu bat", "nếu bật"),
    ("phai hot path", "phải hot path"),
    ("da ngon ngu", "đa ngôn ngữ"),
    ("Mo http", "Mở http"),
    ("de gay", "dễ gây"),
    ("hieu nham", "hiểu nhầm"),
    ("luon label", "luôn label"),
    ("moi truong", "môi trường"),
    ("can can bang", "cần cân bằng"),
    ("uu tien", "ưu tiên"),
    ("dung route", "đúng route"),
    ("giu lazy", "giữ lazy"),
    ("khi nghi ngo", "khi nghi ngờ"),
    ("moi chuoi", "mọi chuỗi"),
    ("qua key", "qua key"),
    ("truoc merge", "trước merge"),
    ("Truoc staging", "Trước staging"),
    ("chong backend that", "chống backend thật"),
    ("Do tin cay", "Độ tin cậy"),
    ("phu thuoc", "phụ thuộc"),
    ("on dinh", "ổn định"),
    ("va evidence", "và evidence"),
    ("nang release", "nâng release"),
    ("len production", "lên production"),
    ("tom tat", "tóm tắt"),
    ("tham chieu", "tham chiếu"),
    ("muc 4", "mục 4"),
    # Backend-ish
    ("trung tam cua duong", "trung tâm của đường"),
    ("Nhan telemetry", "Nhận telemetry"),
    ("tu ClientPLC", "từ ClientPLC"),
    ("danh gia", "đánh giá"),
    ("quan ly", "quản lý"),
    ("khi bat capture", "khi bật capture"),
    ("voi nhieu secret", "với nhiều secret"),
    ("khong thay the", "không thay thế"),
    ("tiep tuc", "tiếp tục"),
    ("khi ODF", "khi ODF"),
    ("nguon su that", "nguồn sự thật"),
    ("path rieng", "path riêng"),
    ("process rieng", "process riêng"),
    ("doc REST", "đọc REST"),
    ("vao MQTT", "vào MQTT"),
    ("chuan hoa", "chuẩn hóa"),
    ("tu Configuration", "từ Configuration"),
    ("sau transaction nguon", "sau transaction nguồn"),
    ("dinh ky cap nhat", "định kỳ cập nhật"),
    ("co the push", "có thể push"),
    ("cung intent", "cùng intent"),
    ("chi la khai bao", "chỉ là khai báo"),
    ("khong mo ta", "không mô tả"),
    ("nhu runtime", "như runtime"),
    ("co history", "có history"),
    ("ket hop", "kết hợp"),
    ("khong luu", "không lưu"),
    ("mot lan", "một lần"),
    ("bang policy", "bằng policy"),
    ("hien single", "hiện single"),
    ("chi trust", "chỉ trust"),
    ("cau hinh.", "cấu hình."),
    ("do fusion-adapter", "do fusion-adapter"),
    ("khong tich luy", "không tích lũy"),
    ("khi tenant", "khi tenant"),
    ("chua san sang", "chưa sẵn sàng"),
    ("sua ket noi roi", "sửa kết nối rồi"),
    ("khong tu load", "không tự load"),
    ("dung env", "dùng env"),
    ("chinh thuc o", "chính thức ở"),
    ("Khong start", "Không start"),
    ("Khong thay telemetry", "Không thấy telemetry"),
    ("van phai nhan", "vẫn phải nhận"),
    ("sau khi target", "sau khi target"),
    ("giu Capture", "giữ Capture"),
    ("tat Dispatch", "tắt Dispatch"),
    ("neu identity", "nếu identity"),
    ("Doc lap migration", "Độc lập migration"),
    ("checklist cutover rieng", "checklist cutover riêng"),
    ("khong duoc marketing", "không được marketing"),
    ("nhu feature live", "như feature live"),
    ("moi admin", "mọi admin"),
    ("truoc pilot", "trước pilot"),
    ("la diem manh", "là điểm mạnh"),
    ("cho den khi", "cho đến khi"),
    ("hoan tat", "hoàn tất"),
    # Odysseus
    ("la self-hosted", "là self-hosted"),
    ("TUY CHON", "TÙY CHỌN"),
    ("khong thuoc core", "không thuộc core"),
    ("khong thay backend", "không thay backend"),
    ("khong doc DB", "không đọc DB"),
    ("nha may truc tiep", "nhà máy trực tiếp"),
    ("chan MQTT", "chặn MQTT"),
    ("thu gon", "thu gọn"),
    ("ca nhan", "cá nhân"),
    ("de tap trung", "để tập trung"),
    ("neu ro", "nêu rõ"),
    ("Khong connection", "Không connection"),
    ("trong Odysseus", "trong Odysseus"),
    ("Secrets tach", "Secrets tách"),
    ("khac MKZ", "khác MKZ"),
    ("Khong dua", "Không đưa"),
    ("ra frontend", "ra frontend"),
    ("co y khong", "cố ý không"),
    ("cho den khi co", "cho đến khi có"),
    ("Lop ung dung", "Lớp ứng dụng"),
    ("ho tro tools", "hỗ trợ tools"),
    ("kiem soat", "kiểm soát"),
    ("tranh hang", "tránh hang"),
    ("ho tro knowledge", "hỗ trợ knowledge"),
    ("goi y model", "gợi ý model"),
    ("theo hardware", "theo hardware"),
    ("co the tat", "có thể tắt"),
    ("bang fii-chat", "bằng fii-chat"),
    ("hoac internal", "hoặc internal"),
    ("ke ca localhost", "kể cả localhost"),
    ("co policy rieng", "có policy riêng"),
    ("Tu choi", "Từ chối"),
    ("khong multi-tenant", "không multi-tenant"),
    ("hien tai", "hiện tại"),
    ("khuyen nghi monorepo", "khuyến nghị monorepo"),
    ("bo email", "bỏ email"),
    ("giu chat", "giữ chat"),
    ("Bat Chroma", "Bật Chroma"),
    ("khi can RAG", "khi cần RAG"),
    ("hoac:", "hoặc:"),
    ("mo http", "mở http"),
    ("trong logs", "trong logs"),
    ("chi tiet:", "chi tiết:"),
    ("Giu auth", "Giữ auth"),
    ("khong public", "không public"),
    ("ngoai Git", "ngoài Git"),
    ("cho keys", "cho keys"),
    ("han che", "hạn chế"),
    ("tren host", "trên host"),
    ("doc truoc", "đọc trước"),
    ("cho OT", "cho OT"),
    ("quy mo lon", "quy mô lớn"),
    ("hang tram", "hàng trăm"),
    ("theo subset", "theo subset"),
    ("lien quan", "liên quan"),
    ("co the start", "có thể start"),
    ("cung stack", "cùng stack"),
    ("su co Odysseus", "sự cố Odysseus"),
    ("khong duoc lam fail", "không được làm fail"),
    ("han che multi-user", "hạn chế multi-user"),
    ("can model auth", "cần model auth"),
    ("tot hon", "tốt hơn"),
    ("truoc production", "trước production"),
    ("bat buoc.", "bắt buộc."),
    ("neu distribute", "nếu distribute"),
    ("khong thay sensor", "không thay sensor"),
    ("van authoritative", "vẫn authoritative"),
    ("Khuyen nghi", "Khuyến nghị"),
    ("bo sung", "bổ sung"),
    ("nhung khong", "nhưng không"),
    ("loi giam sat", "lõi giám sát"),
    ("nha may", "nhà máy"),
    ("Dung dung", "Dùng đúng"),
    ("secrets tach", "secrets tách"),
    ("va khong nang", "và không nâng"),
    ("dua tren", "dựa trên"),
    ("doc lap voi", "độc lập với"),
    # ODF
    ("la nen tang open-source", "là nền tảng open-source"),
    ("cho governed", "cho governed"),
    ("va visual collaboration", "và visual collaboration"),
    ("co hai be mat", "có hai bề mặt"),
    ("day du", "đầy đủ"),
    ("cho preview", "cho preview"),
    ("khong noi OT", "không nối OT"),
    ("khong thuc thi industrial", "không thực thi industrial"),
    ("khi chua review", "khi chưa review"),
    ("an toan doc lap", "an toàn độc lập"),
    ("Voi FII", "Với FII"),
    ("du lieu vao", "dữ liệu vào"),
    ("tu backend", "từ backend"),
    ("ngoai hot path", "ngoài hot path"),
    ("la hai co", "là hai cờ"),
    ("doc lap.", "độc lập."),
    ("khong duoc dung", "không được dừng"),
    ("tren outbox", "trên outbox"),
    ("chon mot", "chọn một"),
    ("thieu identity", "thiếu identity"),
    ("don gian", "đơn giản"),
    ("doc lap.", "độc lập."),
    ("mot backend", "một backend"),
    ("moi process", "mỗi process"),
    ("dung Postgres", "dùng Postgres"),
    ("Khong fallback", "Không fallback"),
    ("cho authoritative", "cho authoritative"),
    ("chi opt-in fixture", "chỉ opt-in fixture"),
    ("trong transaction nghiep vu", "trong transaction nghiệp vụ"),
    ("khi telemetry", "khi telemetry"),
    ("hop le", "hợp lệ"),
    ("truoc khi bat", "trước khi bật"),
    ("khong phai staging", "không phải staging"),
    ("truoc restart", "trước restart"),
    ("dung adapter", "dừng adapter"),
    ("giu pending", "giữ pending"),
    ("sua identity", "sửa identity"),
    ("bat lai", "bật lại"),
    ("khi san sang", "khi sẵn sàng"),
    ("cho multi-tenant", "cho multi-tenant"),
    ("truoc OT", "trước OT"),
    ("rieng.", "riêng."),
    ("Luon tach", "Luôn tách"),
    ("Khong bat Dispatch", "Không bật Dispatch"),
    ("truoc tenant", "trước tenant"),
    ("Khong sua third_party", "Không sửa third_party"),
    ("de chua secret", "để chứa secret"),
    ("can human review", "cần human review"),
    ("truoc trust", "trước trust"),
    ("doc lap:", "độc lập:"),
    ("khong dong nghia", "không đồng nghĩa"),
    ("cung cap", "cung cấp"),
    ("co provenance", "có provenance"),
    ("va duong multi", "và đường multi"),
    ("la secondary delivery", "là secondary delivery"),
    ("thiet ke dung", "thiết kế đúng"),
    ("khi Capture", "khi Capture"),
    ("va operations van song", "và operations vẫn sống"),
    ("neu ODF down", "nếu ODF down"),
    ("dung preview", "dùng preview"),
    ("khong over-claim", "không over-claim"),
]


def run(args):
    r = subprocess.run(
        args,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return r.returncode, r.stdout, r.stderr


def main():
    for file in FILES:
        code, out, err = run(["officecli", "open", file])
        if code != 0:
            print("open fail", file, err or out)
            continue
        for old, new in PAIRS:
            run(["officecli", "set", file, "/", "--find", old, "--replace", new])
        code, out, err = run(["officecli", "save", file])
        if code != 0:
            print("save fail", file, err or out)
        run(["officecli", "close", file])
        run(["officecli", "validate", file])
        print("OK", file)


if __name__ == "__main__":
    main()
