//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLC.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System uptime.
        /// </summary>
        public static string activeContinuous {
            get {
                return ResourceManager.GetString("activeContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ActiveRead].
        /// </summary>
        public static string ActiveRead {
            get {
                return ResourceManager.GetString("ActiveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Address].
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Alias].
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AliasName].
        /// </summary>
        public static string AliasName {
            get {
                return ResourceManager.GetString("AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ApplyError].
        /// </summary>
        public static string ApplyError {
            get {
                return ResourceManager.GetString("ApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ApplySuccess].
        /// </summary>
        public static string ApplySuccess {
            get {
                return ResourceManager.GetString("ApplySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ApplySuccessTitle].
        /// </summary>
        public static string ApplySuccessTitle {
            get {
                return ResourceManager.GetString("ApplySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AppSettings].
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AutoScroll].
        /// </summary>
        public static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AvailabilityLabel].
        /// </summary>
        public static string AvailabilityLabel {
            get {
                return ResourceManager.GetString("AvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AvgSpeedLabel].
        /// </summary>
        public static string AvgSpeedLabel {
            get {
                return ResourceManager.GetString("AvgSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnAdd].
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnApplyText].
        /// </summary>
        public static string BtnApplyText {
            get {
                return ResourceManager.GetString("BtnApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnCancel].
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnDelete].
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnRefreshText].
        /// </summary>
        public static string BtnRefreshText {
            get {
                return ResourceManager.GetString("BtnRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnSave].
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnSaveConfig].
        /// </summary>
        public static string BtnSaveConfig {
            get {
                return ResourceManager.GetString("BtnSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnTestReadText].
        /// </summary>
        public static string BtnTestReadText {
            get {
                return ResourceManager.GetString("BtnTestReadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BtnUpdate].
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Uptime.
        /// </summary>
        public static string Card_ComputerRuntime {
            get {
                return ResourceManager.GetString("Card.ComputerRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Card.ComputerUptimeSub].
        /// </summary>
        public static string Card_ComputerUptimeSub {
            get {
                return ResourceManager.GetString("Card.ComputerUptimeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status.
        /// </summary>
        public static string Card_MachineStatus {
            get {
                return ResourceManager.GetString("Card.MachineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE.
        /// </summary>
        public static string Card_OeePerformance {
            get {
                return ResourceManager.GetString("Card.OeePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Card.OeeTitle].
        /// </summary>
        public static string Card_OeeTitle {
            get {
                return ResourceManager.GetString("Card.OeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Card.PlcConnectionTimeSub].
        /// </summary>
        public static string Card_PlcConnectionTimeSub {
            get {
                return ResourceManager.GetString("Card.PlcConnectionTimeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Connection Time.
        /// </summary>
        public static string Card_PlcRuntime {
            get {
                return ResourceManager.GetString("Card.PlcRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Card.PlcRuntimeTitleLabel].
        /// </summary>
        public static string Card_PlcRuntimeTitleLabel {
            get {
                return ResourceManager.GetString("Card.PlcRuntimeTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Production.
        /// </summary>
        public static string Card_ShiftProduction {
            get {
                return ResourceManager.GetString("Card.ShiftProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Card.ShiftProductionValue].
        /// </summary>
        public static string Card_ShiftProductionValue {
            get {
                return ResourceManager.GetString("Card.ShiftProductionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CboItemDay].
        /// </summary>
        public static string CboItemDay {
            get {
                return ResourceManager.GetString("CboItemDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CboItemNight].
        /// </summary>
        public static string CboItemNight {
            get {
                return ResourceManager.GetString("CboItemNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgAlarmsHelp].
        /// </summary>
        public static string CfgAlarmsHelp {
            get {
                return ResourceManager.GetString("CfgAlarmsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgBtnAdd].
        /// </summary>
        public static string CfgBtnAdd {
            get {
                return ResourceManager.GetString("CfgBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgBtnDelete].
        /// </summary>
        public static string CfgBtnDelete {
            get {
                return ResourceManager.GetString("CfgBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgBtnDownloadTemplate].
        /// </summary>
        public static string CfgBtnDownloadTemplate {
            get {
                return ResourceManager.GetString("CfgBtnDownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgBtnExportAlarm].
        /// </summary>
        public static string CfgBtnExportAlarm {
            get {
                return ResourceManager.GetString("CfgBtnExportAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgBtnImportAlarm].
        /// </summary>
        public static string CfgBtnImportAlarm {
            get {
                return ResourceManager.GetString("CfgBtnImportAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuClose].
        /// </summary>
        public static string CfgMnuClose {
            get {
                return ResourceManager.GetString("CfgMnuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuExportCsv].
        /// </summary>
        public static string CfgMnuExportCsv {
            get {
                return ResourceManager.GetString("CfgMnuExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuFile].
        /// </summary>
        public static string CfgMnuFile {
            get {
                return ResourceManager.GetString("CfgMnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuImportExcel].
        /// </summary>
        public static string CfgMnuImportExcel {
            get {
                return ResourceManager.GetString("CfgMnuImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuNew].
        /// </summary>
        public static string CfgMnuNew {
            get {
                return ResourceManager.GetString("CfgMnuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuOpen].
        /// </summary>
        public static string CfgMnuOpen {
            get {
                return ResourceManager.GetString("CfgMnuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuSave].
        /// </summary>
        public static string CfgMnuSave {
            get {
                return ResourceManager.GetString("CfgMnuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgMnuSaveAs].
        /// </summary>
        public static string CfgMnuSaveAs {
            get {
                return ResourceManager.GetString("CfgMnuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgOthersHelp].
        /// </summary>
        public static string CfgOthersHelp {
            get {
                return ResourceManager.GetString("CfgOthersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgProductsHelp].
        /// </summary>
        public static string CfgProductsHelp {
            get {
                return ResourceManager.GetString("CfgProductsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CfgStatusHelp].
        /// </summary>
        public static string CfgStatusHelp {
            get {
                return ResourceManager.GetString("CfgStatusHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Production by Shift.
        /// </summary>
        public static string Chart_HourlyProduction {
            get {
                return ResourceManager.GetString("Chart.HourlyProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Chart.HourlyProductionTitle].
        /// </summary>
        public static string Chart_HourlyProductionTitle {
            get {
                return ResourceManager.GetString("Chart.HourlyProductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No production data.
        /// </summary>
        public static string Chart_NoProductionData {
            get {
                return ResourceManager.GetString("Chart.NoProductionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0} products/hour.
        /// </summary>
        public static string Chart_Target {
            get {
                return ResourceManager.GetString("Chart.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ClearLog].
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ColAlarmName].
        /// </summary>
        public static string ColAlarmName {
            get {
                return ResourceManager.GetString("ColAlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ColCurrentValue].
        /// </summary>
        public static string ColCurrentValue {
            get {
                return ResourceManager.GetString("ColCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ColDataType].
        /// </summary>
        public static string ColDataType {
            get {
                return ResourceManager.GetString("ColDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ColOtherParamName].
        /// </summary>
        public static string ColOtherParamName {
            get {
                return ResourceManager.GetString("ColOtherParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ColParamName].
        /// </summary>
        public static string ColParamName {
            get {
                return ResourceManager.GetString("ColParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ColPlcAddr].
        /// </summary>
        public static string ColPlcAddr {
            get {
                return ResourceManager.GetString("ColPlcAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ComputerInfo].
        /// </summary>
        public static string ComputerInfo {
            get {
                return ResourceManager.GetString("ComputerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ConfigStatusActive].
        /// </summary>
        public static string ConfigStatusActive {
            get {
                return ResourceManager.GetString("ConfigStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ConnectionConfig].
        /// </summary>
        public static string ConnectionConfig {
            get {
                return ResourceManager.GetString("ConnectionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous connection time.
        /// </summary>
        public static string cumulativeConnection {
            get {
                return ResourceManager.GetString("cumulativeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        public static string Dashboard_Date {
            get {
                return ResourceManager.GetString("Dashboard.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine: {0}.
        /// </summary>
        public static string Dashboard_Machine {
            get {
                return ResourceManager.GetString("Dashboard.Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Dashboard.MainTitle].
        /// </summary>
        public static string Dashboard_MainTitle {
            get {
                return ResourceManager.GetString("Dashboard.MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle: {0} ms.
        /// </summary>
        public static string Dashboard_ReadCycle {
            get {
                return ResourceManager.GetString("Dashboard.ReadCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift: {0}.
        /// </summary>
        public static string Dashboard_Shift {
            get {
                return ResourceManager.GetString("Dashboard.Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time Performance Monitoring.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DataTableTitle].
        /// </summary>
        public static string DataTableTitle {
            get {
                return ResourceManager.GetString("DataTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DataType].
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Disconnected].
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enabled].
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ErrorOpenExcelImport].
        /// </summary>
        public static string ErrorOpenExcelImport {
            get {
                return ResourceManager.GetString("ErrorOpenExcelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ErrorReadConfig].
        /// </summary>
        public static string ErrorReadConfig {
            get {
                return ResourceManager.GetString("ErrorReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ExpectedSpeed].
        /// </summary>
        public static string ExpectedSpeed {
            get {
                return ResourceManager.GetString("ExpectedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU: {0:F1}%.
        /// </summary>
        public static string Footer_Cpu {
            get {
                return ResourceManager.GetString("Footer.Cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated: {0}.
        /// </summary>
        public static string Footer_LastUpdated {
            get {
                return ResourceManager.GetString("Footer.LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM: {0}.
        /// </summary>
        public static string Footer_Ram {
            get {
                return ResourceManager.GetString("Footer.Ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime: {0}.
        /// </summary>
        public static string Footer_Uptime {
            get {
                return ResourceManager.GetString("Footer.Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Footer_Version {
            get {
                return ResourceManager.GetString("Footer.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pcs/h.
        /// </summary>
        public static string Format_PcsPerHour {
            get {
                return ResourceManager.GetString("Format.PcsPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Format.ProductsUnit].
        /// </summary>
        public static string Format_ProductsUnit {
            get {
                return ResourceManager.GetString("Format.ProductsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GeneralInfo].
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LabelBrands].
        /// </summary>
        public static string LabelBrands {
            get {
                return ResourceManager.GetString("LabelBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LabelFontSize].
        /// </summary>
        public static string LabelFontSize {
            get {
                return ResourceManager.GetString("LabelFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LabelLang].
        /// </summary>
        public static string LabelLang {
            get {
                return ResourceManager.GetString("LabelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LabelMode].
        /// </summary>
        public static string LabelMode {
            get {
                return ResourceManager.GetString("LabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LabelStart].
        /// </summary>
        public static string LabelStart {
            get {
                return ResourceManager.GetString("LabelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LabelTheme].
        /// </summary>
        public static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Large].
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LastSignalPrefix].
        /// </summary>
        public static string LastSignalPrefix {
            get {
                return ResourceManager.GetString("LastSignalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LastUpdate].
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LineIdLabel].
        /// </summary>
        public static string LineIdLabel {
            get {
                return ResourceManager.GetString("LineIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LineNameLabel].
        /// </summary>
        public static string LineNameLabel {
            get {
                return ResourceManager.GetString("LineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LineOrderLabel].
        /// </summary>
        public static string LineOrderLabel {
            get {
                return ResourceManager.GetString("LineOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LoadedAddresses].
        /// </summary>
        public static string LoadedAddresses {
            get {
                return ResourceManager.GetString("LoadedAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LocalWebServerLabel].
        /// </summary>
        public static string LocalWebServerLabel {
            get {
                return ResourceManager.GetString("LocalWebServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LogTitle].
        /// </summary>
        public static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MachineIdLabel].
        /// </summary>
        public static string MachineIdLabel {
            get {
                return ResourceManager.GetString("MachineIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MachineNameLabel].
        /// </summary>
        public static string MachineNameLabel {
            get {
                return ResourceManager.GetString("MachineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Medium].
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Never].
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NewConfig].
        /// </summary>
        public static string NewConfig {
            get {
                return ResourceManager.GetString("NewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NoConfigAddresses].
        /// </summary>
        public static string NoConfigAddresses {
            get {
                return ResourceManager.GetString("NoConfigAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Notice].
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OeeLabel].
        /// </summary>
        public static string OeeLabel {
            get {
                return ResourceManager.GetString("OeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OpenConfigSuccess].
        /// </summary>
        public static string OpenConfigSuccess {
            get {
                return ResourceManager.GetString("OpenConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OpenConfigSuccessTitle].
        /// </summary>
        public static string OpenConfigSuccessTitle {
            get {
                return ResourceManager.GetString("OpenConfigSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OpenConfigTitle].
        /// </summary>
        public static string OpenConfigTitle {
            get {
                return ResourceManager.GetString("OpenConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability (A).
        /// </summary>
        public static string Performance_Availability {
            get {
                return ResourceManager.GetString("Performance.Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Speed:.
        /// </summary>
        public static string Performance_AverageSpeed {
            get {
                return ResourceManager.GetString("Performance.AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance (P).
        /// </summary>
        public static string Performance_Performance {
            get {
                return ResourceManager.GetString("Performance.Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Speed:.
        /// </summary>
        public static string Performance_RatedSpeed {
            get {
                return ResourceManager.GetString("Performance.RatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Performance.SummaryTitle].
        /// </summary>
        public static string Performance_SummaryTitle {
            get {
                return ResourceManager.GetString("Performance.SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Performance Details.
        /// </summary>
        public static string Performance_Title {
            get {
                return ResourceManager.GetString("Performance.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PerformanceLabel].
        /// </summary>
        public static string PerformanceLabel {
            get {
                return ResourceManager.GetString("PerformanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcAddrConfigTitle].
        /// </summary>
        public static string PlcAddrConfigTitle {
            get {
                return ResourceManager.GetString("PlcAddrConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcAddress].
        /// </summary>
        public static string PlcAddress {
            get {
                return ResourceManager.GetString("PlcAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcBrand].
        /// </summary>
        public static string PlcBrand {
            get {
                return ResourceManager.GetString("PlcBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcBrandLabel].
        /// </summary>
        public static string PlcBrandLabel {
            get {
                return ResourceManager.GetString("PlcBrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcConfig].
        /// </summary>
        public static string PlcConfig {
            get {
                return ResourceManager.GetString("PlcConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcGroupTitle].
        /// </summary>
        public static string PlcGroupTitle {
            get {
                return ResourceManager.GetString("PlcGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcIp].
        /// </summary>
        public static string PlcIp {
            get {
                return ResourceManager.GetString("PlcIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcIpLabel].
        /// </summary>
        public static string PlcIpLabel {
            get {
                return ResourceManager.GetString("PlcIpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcPort].
        /// </summary>
        public static string PlcPort {
            get {
                return ResourceManager.GetString("PlcPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcPortLabel].
        /// </summary>
        public static string PlcPortLabel {
            get {
                return ResourceManager.GetString("PlcPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcProtocol].
        /// </summary>
        public static string PlcProtocol {
            get {
                return ResourceManager.GetString("PlcProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcStatusConnected].
        /// </summary>
        public static string PlcStatusConnected {
            get {
                return ResourceManager.GetString("PlcStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcStatusError].
        /// </summary>
        public static string PlcStatusError {
            get {
                return ResourceManager.GetString("PlcStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcStatusNotConnected].
        /// </summary>
        public static string PlcStatusNotConnected {
            get {
                return ResourceManager.GetString("PlcStatusNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlcUptimeLabel].
        /// </summary>
        public static string PlcUptimeLabel {
            get {
                return ResourceManager.GetString("PlcUptimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PromptNewConfig].
        /// </summary>
        public static string PromptNewConfig {
            get {
                return ResourceManager.GetString("PromptNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PromptOpenConfig].
        /// </summary>
        public static string PromptOpenConfig {
            get {
                return ResourceManager.GetString("PromptOpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [QueryBtn].
        /// </summary>
        public static string QueryBtn {
            get {
                return ResourceManager.GetString("QueryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ReadError].
        /// </summary>
        public static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ReadInterval].
        /// </summary>
        public static string ReadInterval {
            get {
                return ResourceManager.GetString("ReadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ReadIntervalLabel].
        /// </summary>
        public static string ReadIntervalLabel {
            get {
                return ResourceManager.GetString("ReadIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RefreshConfig].
        /// </summary>
        public static string RefreshConfig {
            get {
                return ResourceManager.GetString("RefreshConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Reload].
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ReloadedConfig].
        /// </summary>
        public static string ReloadedConfig {
            get {
                return ResourceManager.GetString("ReloadedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SaveChangesTitle].
        /// </summary>
        public static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SaveConfig].
        /// </summary>
        public static string SaveConfig {
            get {
                return ResourceManager.GetString("SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SaveFileError].
        /// </summary>
        public static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SelectAlarmDelete].
        /// </summary>
        public static string SelectAlarmDelete {
            get {
                return ResourceManager.GetString("SelectAlarmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SelectDateError].
        /// </summary>
        public static string SelectDateError {
            get {
                return ResourceManager.GetString("SelectDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SelectDateLabel].
        /// </summary>
        public static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SelectShiftLabel].
        /// </summary>
        public static string SelectShiftLabel {
            get {
                return ResourceManager.GetString("SelectShiftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerConfig].
        /// </summary>
        public static string ServerConfig {
            get {
                return ResourceManager.GetString("ServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerHost].
        /// </summary>
        public static string ServerHost {
            get {
                return ResourceManager.GetString("ServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerHostLabel].
        /// </summary>
        public static string ServerHostLabel {
            get {
                return ResourceManager.GetString("ServerHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerPort].
        /// </summary>
        public static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerPortLabel].
        /// </summary>
        public static string ServerPortLabel {
            get {
                return ResourceManager.GetString("ServerPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerStatusConnected].
        /// </summary>
        public static string ServerStatusConnected {
            get {
                return ResourceManager.GetString("ServerStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerStatusConnecting].
        /// </summary>
        public static string ServerStatusConnecting {
            get {
                return ResourceManager.GetString("ServerStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ServerStatusDisconnected].
        /// </summary>
        public static string ServerStatusDisconnected {
            get {
                return ResourceManager.GetString("ServerStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SetupTitle].
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ShiftAvgSpeed].
        /// </summary>
        public static string ShiftAvgSpeed {
            get {
                return ResourceManager.GetString("ShiftAvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ShiftDateLabel].
        /// </summary>
        public static string ShiftDateLabel {
            get {
                return ResourceManager.GetString("ShiftDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ShiftName].
        /// </summary>
        public static string ShiftName {
            get {
                return ResourceManager.GetString("ShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ShiftNameLabel].
        /// </summary>
        public static string ShiftNameLabel {
            get {
                return ResourceManager.GetString("ShiftNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Small].
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Status_Offline {
            get {
                return ResourceManager.GetString("Status.Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [StatusUpdating].
        /// </summary>
        public static string StatusUpdating {
            get {
                return ResourceManager.GetString("StatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STT].
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Success].
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SuccessSave].
        /// </summary>
        public static string SuccessSave {
            get {
                return ResourceManager.GetString("SuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SuccessSaveConfig].
        /// </summary>
        public static string SuccessSaveConfig {
            get {
                return ResourceManager.GetString("SuccessSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysDashboard].
        /// </summary>
        public static string SysDashboard {
            get {
                return ResourceManager.GetString("SysDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysDataTable].
        /// </summary>
        public static string SysDataTable {
            get {
                return ResourceManager.GetString("SysDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysHistoryQuery].
        /// </summary>
        public static string SysHistoryQuery {
            get {
                return ResourceManager.GetString("SysHistoryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysLiveErrors].
        /// </summary>
        public static string SysLiveErrors {
            get {
                return ResourceManager.GetString("SysLiveErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysLiveStatus].
        /// </summary>
        public static string SysLiveStatus {
            get {
                return ResourceManager.GetString("SysLiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysLog].
        /// </summary>
        public static string SysLog {
            get {
                return ResourceManager.GetString("SysLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SysSettings].
        /// </summary>
        public static string SysSettings {
            get {
                return ResourceManager.GetString("SysSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [System.ClientTitle].
        /// </summary>
        public static string System_ClientTitle {
            get {
                return ResourceManager.GetString("System.ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TabAlarmsText].
        /// </summary>
        public static string TabAlarmsText {
            get {
                return ResourceManager.GetString("TabAlarmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TabOthersText].
        /// </summary>
        public static string TabOthersText {
            get {
                return ResourceManager.GetString("TabOthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TabProductsText].
        /// </summary>
        public static string TabProductsText {
            get {
                return ResourceManager.GetString("TabProductsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TabStatusText].
        /// </summary>
        public static string TabStatusText {
            get {
                return ResourceManager.GetString("TabStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TargetProgressPattern].
        /// </summary>
        public static string TargetProgressPattern {
            get {
                return ResourceManager.GetString("TargetProgressPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TelemetryCpuCores].
        /// </summary>
        public static string TelemetryCpuCores {
            get {
                return ResourceManager.GetString("TelemetryCpuCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TelemetryCpuUsage].
        /// </summary>
        public static string TelemetryCpuUsage {
            get {
                return ResourceManager.GetString("TelemetryCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TelemetryOS].
        /// </summary>
        public static string TelemetryOS {
            get {
                return ResourceManager.GetString("TelemetryOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TelemetryRamUsage].
        /// </summary>
        public static string TelemetryRamUsage {
            get {
                return ResourceManager.GetString("TelemetryRamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TelemetryUptime].
        /// </summary>
        public static string TelemetryUptime {
            get {
                return ResourceManager.GetString("TelemetryUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TestConnection].
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TitleAppConfig].
        /// </summary>
        public static string TitleAppConfig {
            get {
                return ResourceManager.GetString("TitleAppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TitleAppSettings].
        /// </summary>
        public static string TitleAppSettings {
            get {
                return ResourceManager.GetString("TitleAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TotalQtyLabel].
        /// </summary>
        public static string TotalQtyLabel {
            get {
                return ResourceManager.GetString("TotalQtyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Type].
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        public static string unitProducts {
            get {
                return ResourceManager.GetString("unitProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UnsavedChangesPrompt].
        /// </summary>
        public static string UnsavedChangesPrompt {
            get {
                return ResourceManager.GetString("UnsavedChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UpdatedTime].
        /// </summary>
        public static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Value].
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Version].
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WaitingRead].
        /// </summary>
        public static string WaitingRead {
            get {
                return ResourceManager.GetString("WaitingRead", resourceCulture);
            }
        }
    }
}
